
#GET http://localhost:4004/rest/productshop/MyFunction(name='BMW')


#POST http://localhost:4004/odata/v4/productshop/Supplier
#Content-Type: application/json



#GET http://localhost:4004/odata/v4/productshop/Product

POST http://localhost:4004/odata/v4/productshop/Product
Content-Type: application/json

{
  "name": "MG Hector",
  "stock": 60
}




